# Note that the service name must match what is in the corresponding docker compose
environment_path: .

# Path to directory containing variable values for each host
host_vars_path: host_vars

# This must match exactly with the docker-compose.yml file
services:
  nfd:
    template_path: templates/nfd
    render_path: dist/nfd
    init_exec: ['/bin/bash', '/config/nfd-init.sh']

  ndnpingserver:
    template_path: templates/ndnpingserver
    render_path: dist/ndnpingserver

  nlsr:
    template_path: templates/nlsr
    render_path: dist/nlsr