services:
  ndnping:
    build:
      context: ./ndn-tools
    tty: true
    volumes:
      - ./nfd/rendered_templates:/run/nfd
      - ./ndnping/rendered_templates:/ndnping
    depends_on:
      nfd:
        condition: service_healthy
    links:
      - nfd
  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - ./nfd/rendered_templates:/run/nfd
      - ./nfd/rendered_templates:/config
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
