services:
  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - ./dist/nfd-sock:/run/nfd
      - ./dist/nfd:/config
    network_mode: host
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  # ndnping:
  #   build:
  #     context: ./ndn-tools
  #   tty: true
  #   volumes:
  #     - /run/nfd:/run/nfd
  #     - ./dist/ndnping:/ndnping
  #   depends_on:
  #     nfd:
  #       condition: service_healthy
  #   links:
  #     - nfd
