services:
  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/nfd:/config
    network_mode: host
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  ndnpingserver:
    image: ghcr.io/pulsejet/ndn-tools@sha256:342a3d45abc7ae81401789d14df083f620c7b637fe06a08c321ab2353057c032
    tty: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndnpingserver:/ndnpingserver
    entrypoint: /bin/bash
    command: /ndnpingserver/entrypoint.sh
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]
