services:
  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - /run/nfd:/run/nfd
      - /etc/ndn/keys/anchors:/keys/anchors
      - ./dist/nfd:/config
    ports:
      - "6363:6363"
      - "6363:6363/udp"
      - "9696:9696"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  ndnpingserver:
    image: ghcr.io/pulsejet/ndn-tools:latest
    tty: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndnpingserver:/ndnpingserver
    entrypoint: /bin/bash
    command: /ndnpingserver/entrypoint.sh
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  nlsr:
    image: ghcr.io/pulsejet/nlsr@sha256:25776438396b506b7cae8b00c94d1e2b0b0a7a005e40c09afa6436b5922574ef
    volumes:
      - /run/nfd:/run/nfd
      - /etc/ndn/nlsr/keys:/keys
      - /etc/ndn/keys/anchors:/keys/anchors
      - /var/lib/ndn/nlsr:/private
      - ./dist/nlsr:/config
    environment:
      HOME: /private
      NDN_LOG: nlsr.*=DEBUG
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]
