name: testbed
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./dist/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./dist/caddy/data:/data
      - ./dist/caddy/config:/config

  nfd:
    image: ghcr.io/named-data/nfd:20240420
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - ./anchors:/keys/anchors
      - ./dist/nfd:/config
    ports:
      - "6363:6363"
      - "6363:6363/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  nfd-http-status-server:
    image: ghcr.io/named-data/nfd-status-http-server:20240420
    init: true
    volumes:
      - /run/nfd:/run/nfd
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  ndnpingserver:
    image: ghcr.io/named-data/ndn-tools:20240505
    tty: true
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndnpingserver:/ndnpingserver
    entrypoint: /bin/bash
    command: /ndnpingserver/entrypoint.sh
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  serve-certs:
    image: ghcr.io/yoursunny/ndn6-tools:20240505
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndncert/private/site.ndncert:/certs/site.ndncert
      - ./anchors:/keys/anchors
    entrypoint: /bin/bash
    command: ['-c', 'ndn6-serve-certs /keys/anchors/*.base64  /certs/*.ndncert']
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  nlsr:
    image: ghcr.io/pulsejet/nlsr@sha256:567558e8ce37453f410cf2cdc612c1bf11252de0b935b8b7d5da41ce6381f5de
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - ./anchors:/keys/anchors
      - ./dist/nlsr/private:/private
      - ./dist/nlsr:/config
    environment:
      HOME: /private
      NDN_LOG: nlsr.*=DEBUG
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  ndn-python-repo:
    image: ghcr.io/ucla-irl/ndn-python-repo:20240505
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - /root:/private
      - ./dist/ndn-python-repo:/config
    environment:
      HOME: /private
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  ndncert:
    image: ghcr.io/pulsejet/ndncert:20240506
    init: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndncert/private:/private
      - ./dist/ndncert/ndncert-mail.conf:/etc/ndncert/ndncert-mail.conf
      - ./dist/ndncert:/config
    environment:
      HOME: /private
      NDN_LOG: '*=TRACE'
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]

  http-ca-server:
    image: ghcr.io/ucla-irl/http-ca-server:latest
    init: true
    tty: true
    volumes:
      - /var/lib/ndn/ndncert-ca:/private
      - ./dist/root-ca:/config
    environment:
      HOME: /private
    restart: unless-stopped
