version: '3'
services:
  ping:
    build:
      context: ./ndn-tools
    tty: true        # docker run -t
    volumes:
      - ./nfd:/run/nfd
    depends_on:
      nfd:
        condition: service_healthy
    links:
      - nfd
    entrypoint: /usr/local/bin/ndnping
    command: "/alice"
    
  pingserver:
    build:
      context: ./ndn-tools
    tty: true
    volumes:
      - ./nfd:/run/nfd
    depends_on:
      nfd:
        condition: service_healthy
    links:
      - nfd
    command: /alice

  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - ./nfd:/run/nfd
      - ./nfd:/config
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
