services:
  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/nfd:/config
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  ndnpingserver:
    image: ghcr.io/pulsejet/ndn-tools:latest
    tty: true
    volumes:
      - /run/nfd:/run/nfd
      - ./dist/ndnpingserver:/ndnpingserver
    entrypoint: /bin/bash
    command: /ndnpingserver/entrypoint.sh
    restart: unless-stopped
    depends_on:
      nfd:
        condition: service_healthy
    links: [nfd]
