version: '3'
services:
  ndn6tools:
    build:
      context: .
    tty: true        # docker run -t
    volumes:
      - ./nfd:/run/nfd
    depends_on:
      nfd:
        condition: service_healthy
    links:
      - nfd

  nfd:
    image: ghcr.io/named-data/nfd:latest
    volumes:
      - ./nfd:/run/nfd
      - ./nfd:/config
    healthcheck:
      test: ["CMD", "nfdc", "status"]
      interval: 5s
      timeout: 10s
      retries: 5
