name: Docker
on:
  schedule:
    # twice a month
    - cron: '20 9 5,20 * *'
  workflow_dispatch:

permissions:
  packages: write
  id-token: write

jobs:
  testbed-master:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: testbed-master
      target: testbed-master
